// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Assistant is a dummy AI assistant target.
 */
export interface Assistant {
    "id": string;
    "name": string;
}

/**
 * Role is a dummy role preset. SkillIDs are the skills the preset selects.
 */
export interface Role {
    "id": string;
    "name": string;
    "skillIDs": string[] | null;
}

/**
 * RuntimeInfo describes the host environment and backend status for the info panel.
 */
export interface RuntimeInfo {
    "os": string;
    "arch": string;
    "appVersion": string;
    "goVersion": string;
    "backendStatus": string;
}

/**
 * Skill is a dummy skill entry.
 */
export interface Skill {
    "id": string;
    "name": string;
    "description": string;
}
