// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SkillManagerService exposes the Skill Manager POC operations to the frontend.
 * 
 * IMPORTANT: This is a build/distribution feasibility POC. None of these methods
 * perform real skill operations. They only return dummy data or dummy success
 * messages. There is deliberately no real install, publish, Git, Nexus, auth,
 * PAT handling, auto-update, or assistant detection here.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DeleteSkill pretends to delete a skill. POC only.
 */
export function DeleteSkill(skillID: string): $CancellablePromise<string> {
    return $Call.ByID(1196579899, skillID);
}

/**
 * GetRuntimeInfo returns dummy/real runtime metadata for the info panel.
 * OS, Arch and GoVersion are real (cheap to read); the rest is POC scaffolding.
 */
export function GetRuntimeInfo(): $CancellablePromise<$models.RuntimeInfo> {
    return $Call.ByID(1491907537);
}

/**
 * InstallSkill pretends to install a skill. POC only.
 */
export function InstallSkill(skillID: string): $CancellablePromise<string> {
    return $Call.ByID(3958218013, skillID);
}

/**
 * ListAssistants returns the dummy assistant selector options.
 */
export function ListAssistants(): $CancellablePromise<$models.Assistant[] | null> {
    return $Call.ByID(2038394176);
}

/**
 * ListRoles returns the dummy role presets. Each preset maps to a set of skills.
 * "Select All" is intentionally handled in the frontend, not as a backend role.
 */
export function ListRoles(): $CancellablePromise<$models.Role[] | null> {
    return $Call.ByID(2526797626);
}

/**
 * ListSkills returns the dummy skills list.
 */
export function ListSkills(): $CancellablePromise<$models.Skill[] | null> {
    return $Call.ByID(2183855883);
}

/**
 * UpdateSkill pretends to update a skill. POC only.
 */
export function UpdateSkill(skillID: string): $CancellablePromise<string> {
    return $Call.ByID(315332953, skillID);
}
